# ?????? ? ?? ??
spring.application.name=auth
server.port=${AUTH_PORT:9000}

# MySQL ?????? (?? ?? ?? DB)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/${AUTH_DB_NAME:auth_db}?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

# ??
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.security=TRACE

server.servlet.session.tracking-modes=cookie
server.servlet.session.cookie.name=AUTH_SESSION_ID

## Registration: ?????? ????
#spring.security.oauth2.client.registration.test-client.client-id=test-client
#spring.security.oauth2.client.registration.test-client.client-secret=secret
#spring.security.oauth2.client.registration.test-client.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.test-client.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.test-client.scope=openid,profile,email
#
## Provider: ???? ?? ??(??)? ???? ??? (? ?? ??)
#spring.security.oauth2.client.provider.test-client.authorization-uri=http://localhost:9000/oauth2/authorize
#spring.security.oauth2.client.provider.test-client.token-uri=http://localhost:9000/oauth2/token
#spring.security.oauth2.client.provider.test-client.user-name-attribute=sub
#spring.security.oauth2.client.provider.test-client.jwk-set-uri=http://localhost:9000/oauth2/jwks

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000